### ISSUE TITLE
Support use of unescaped quotes and apostrophes in strings within JSON request

### ISSUE THREAD

**Issue by nicolemitchell** [Comp413-F18/DatelineRice2.0#59]
Currently having an apostrophe in the headline field errors since we insert this raw string directly into the SQL command, and SQL interprets the apostrophes as quotes

**Comment by willkoh** [comment]
https://stackoverflow.com/questions/26331524/how-to-escape-single-quotes-for-sql-insert-when-string-to-insert-is-in-a-user/26333542 

^ from 4 years ago, but looks promising.

**Comment by lucyrfox** [comment]
I think this has been addressed, @nicolemitchell can you confirm and close if so?

**Comment by nicolemitchell** [comment]
https://github.com/Comp413-F18/DatelineRice2.0/pull/53/commits/39a1967dc7ba3ca843b5dfa27451120a6936d498

@ameesh-shah committed this. I will test and close.
