### ISSUE TITLE
Ensure consistency in scope labels (national/local/state/etc)

### ISSUE THREAD

**Issue by nicolemitchell** [Comp413-F18/DatelineRice2.0#60]
Right now the local/state label isn't consistent, so requests return in error if the scope field isn't set to "national"

**Comment by willkoh** [comment]
@nicolemitchell can you specify what you mean by this?

**Comment by nicolemitchell** [comment]
> @nicolemitchell can you specify what you mean by this?

I haven't dug into this issue, but when I was sending a post request with "LOCAL" specified it returned error.

**Comment by willkoh** [comment]
gotcha. must be something wrong with the enum class. will look into it!
